channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=24.0
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pathlib==1.0.1
  - psutil==7.0.0
  - scikit-learn==1.4.1.post1
  - scipy==1.12.0
name: mlflow-env
